version: '3.4'

services:
  omdbweather:
    image: omdbweather/omdbweather:latest
    ports:
      - "8660:8660"
    environment:
      PORT: '8660'
    restart: always
    depends_on:
        - myredis

  myredis:
    image: "redislabs/redisearch:latest"
    container_name: myredis
    ports:
        - 6379:6379

volumes:
  mysql:
  mysql_config:
  myredis:
