version: '3.4'

services:
  omdbweather:
    image: omdbweather/omdbweather:latest
    ports:
      - "8660:8660"
    environment:
      PORT: '8660'
    restart: always
    depends_on:
        - mysqldb

  mysqldb:
    image: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

  myredis:
    image: "redislabs/redisearch:latest"
    container_name: myredis
    ports:
        - 6379:6379

volumes:
  mysql:
  mysql_config:
  myredis:
